<script> // the purpose of this line is so syntax highlighters know this is a script
//// THIS FILE IS AUTOMATICALLY GENERATED!
//// DO NOT EDIT BY HAND!

import { buildApiCaller } from './callers'

// Little shortcut to increase the capability of minifier
const bac = buildApiCaller

var Api = {}

@foreach ($namespacesFlat as $namespace)
Api.{{ $namespace->absName }} = {
@foreach ($namespace->methods() as $method)

    @include('api.codegen.js_doc', compact('method'))
    {{ $method->name }}: bac('{{ $method->absName }}')<?= ($method->isLast)? '' : ',' ?>

@endforeach
}

@endforeach

export default Api
