<script> // the purpose of this line is so syntax highlighters know this is a script
//// THIS FILE IS AUTOMATICALLY GENERATED!
//// DO NOT EDIT BY HAND!

function apiCall(name, params, callback) {
	var input = $.extend({method: name}, params)
	$.ajax({
		url: "/api",
		method: 'POST',
		contentType: "application/json",
		data: JSON.stringify(input)
	}).done(function(data, textStatus) {
		callback(data);
	}).fail(function(jqXHR, textStatus, errorThrown) {
		console.log(textStatus);
		console.log(errorThrown);
	})
}

var Api = {};

@foreach ($namespacesFlat as $namespace)
Api.{{ $namespace->absName }} = {
@foreach ($namespace->methods() as $method)

    @include('api.codegen.js_doc', compact('method'))
    {{ $method->name }}: function(params, callback) {
        apiCall('{{ $method->absName }}', params, callback);
    }<?= ($method->isLast)? '' : ',' ?>

@endforeach
};
@endforeach
