<script> // the purpose of this line is so syntax highlighters know this is a script
//// THIS FILE IS AUTOMATICALLY GENERATED!
//// DO NOT EDIT BY HAND!

var Api = {};

@foreach ($namespacesFlat as $namespace)
Api.{{ $namespace->absName }} = {
@foreach ($namespace->methods() as $method)

    @include('api.codegen.js_doc', compact('method'))
    {{ $method->name }}: function(params, callback) {
        apiCall('{{ $method->absName }}', params, callback);
    }<?= ($method->isLast)? '' : ',' ?>

@endforeach
};
@endforeach
