<script> // the purpose of this line is so syntax highlighters know this is a script
//// THIS FILE IS AUTOMATICALLY GENERATED!
//// DO NOT EDIT BY HAND!

function apiCall(name, params, callback, errback) {
	var input = $.extend({method: name}, params)
    if (!callback) {
        callback = function(data, textStatus) {
            console.log(data);
        };
    }
    if (!errback) {
        errback = function(jqXHR, textStatus, errorThrown) {
            console.log(textStatus);
            console.log(errorThrown);
        };
    }
	return $.ajax({
		url: "/api",
		method: 'POST',
		contentType: "application/json",
		data: JSON.stringify(input)
	}).done(callback).fail(errback);
}

var Api = {};

@foreach ($namespacesFlat as $namespace)
Api.{{ $namespace->absName }} = {
@foreach ($namespace->methods() as $method)

    @include('api.codegen.js_doc', compact('method'))
    {{ $method->name }}: function(params, callback, errback) {
        return apiCall('{{ $method->absName }}', params, (callback || null), (errback || null));
    }<?= ($method->isLast)? '' : ',' ?>

@endforeach
};
@endforeach
