<script> // the purpose of this line is so syntax highlighters know this is a script
<?php $namespaces = array_keys($reportMeta); ?>
//// THIS FILE IS AUTOMATICALLY GENERATED!
//// DO NOT EDIT BY HAND!

{{-- We disable eslint because our aggressive linting doesn't like pure JSON even though it is valid JS --}}
/* eslint-disable */
@foreach ($reportMeta as $namespace)
const {{ $namespace->id }}Report = @json_pretty($namespace->flatEs6ArrayWithVirtualRoot())

@endforeach

{{-- Because blade aggressively chops newlines after a foreach, we need an _extra_ one before this one --}}
/* eslint-enable */


const Reports = {
<?php
for ($i =0; $i < count($namespaces); $i++) {
    $namespace = $reportMeta[$namespaces[$i]];
    echo "    {$namespace->id}: {$namespace->id}Report";
    if ($i != (count($namespaces)-1)) {
        echo ",";
    }
    echo "\n";
}
?>
}

export default Reports
