<script> // the purpose of this line is so syntax highlighters know this is a script
<?php $namespaces = array_keys($reportMeta); ?>
//// THIS FILE IS AUTOMATICALLY GENERATED!
//// DO NOT EDIT BY HAND!

@foreach ($reportMeta as $namespace)
const {{ $namespace->id }}Report = @json_pretty([
    'root' => $namespace->childrenIds(),
    'children' => $namespace->flatEs6Array(),
])
@endforeach


const Reports = {
<?php
for ($i =0; $i < count($namespaces); $i++) {
    $namespace = $reportMeta[$namespaces[$i]];
    echo "    {$namespace->id}: {$namespace->id}Report";
    if ($i != (count($namespaces)-1)) {
        echo ",";
    }
    echo "\n";
}
?>
}

export default Reports
